
name: layout
description: >
  Platformer 2 Ilocode R&D
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: any
  logger: any
  flame: any
  forge2d: any
  wakelock: ^0.6.1+1


  flutter:
    sdk: flutter
  cupertino_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
    - assets/audio/sfx/